# Batch 3 Kaggle Prep — Simple Colab Pipeline

This notebook is a **simplified version** of the larger ETL flow.

It is designed for current goal:

1. download the four Kaggle datasets,
2. keep the relevant CSV files,
3. run a light cleaning/preprocessing pass,
4. export **Batch 3-ready** files,
5. zip them so you can download them from Colab

**Important:** do not hardcode your Kaggle token in the notebook. Use the runtime prompt cell below.

In [ ]:
# ============================================================
# CELL 1: Install Kaggle + prompt for token + create folders
# ============================================================

# Step 1:
# Install the Kaggle CLI.
!pip -q install kaggle

# Step 2:
# Prompt for your Kaggle API token at runtime.
# Do NOT paste the token directly into the notebook source.
import os
import getpass
from pathlib import Path

os.environ["KAGGLE_API_TOKEN"] = getpass.getpass("Enter your Kaggle API token: ")

# Step 3:
# Create a simple folder structure inside the Colab runtime.
# We are keeping everything inside /content so this stays simple.
BASE = Path("/content/batch3_kaggle")
RAW = BASE / "raw"
UNZIPPED = BASE / "unzipped"
READY = BASE / "batch3_ready"
ZIPS = BASE / "zips"

for folder in [RAW, UNZIPPED, READY, ZIPS]:
    folder.mkdir(parents=True, exist_ok=True)

print("Folders created:")
print("RAW     =", RAW)
print("UNZIPPED=", UNZIPPED)
print("READY   =", READY)
print("ZIPS    =", ZIPS)

# Step 4:
# Quick real auth check.
# This should print the files for one dataset if auth worked.
!kaggle datasets files paultimothymooney/stock-market-data

Enter your Kaggle API token: ··········
Folders created:
RAW     = /content/batch3_kaggle/raw
UNZIPPED= /content/batch3_kaggle/unzipped
READY   = /content/batch3_kaggle/batch3_ready
ZIPS    = /content/batch3_kaggle/zips
Next Page Token = CfDJ8CS0IeAoHcJGgSEc27rBbk4RkIhYFe6cS6fRB0Z_30hHL84VNGIXXtUIZDwp1DMZ-OFL7n65qfQKiUcw9JWpWBRjjy916Ut1dFDDQI1_O_NtZWeZGY4DwNdRiwqQorqQgEUvljeFycw4BZF7SF4Wm1GUUpLQcSgNg-1OfRiVvKk
name                                           size  creationDate
------------------------------------------  -------  --------------------------
stock_market_data/forbes2000/csv/A.csv       638996  2023-01-16 21:04:05.439000
stock_market_data/forbes2000/csv/AAALY.csv   257045  2023-01-16 21:04:05.452000
stock_market_data/forbes2000/csv/AACAY.csv   312258  2023-01-16 21:04:05.467000
stock_market_data/forbes2000/csv/AAL.csv     466378  2023-01-16 21:04:05.483000
stock_market_data/forbes2000/csv/AAP.csv     568177  2023-01-16 21:04:05.476000
stock_market_data/forbes2000/csv/AAPL.csv   1199541  2023-01-16 21:04:05.527000
stock_market_data/forbes2000/csv/ABBV.csv    267639  2023-01-16 21:04:05.525000
stock_market_data/forbes2000/csv/ABC.csv     693870  2023-01-16 21:04:05.513000
stock_market_data/forbes2000/csv/ABLT.csv    142796  2023-01-16 21:04:05.498000
stock_market_data/forbes2000/csv/ABT.csv    1184468  2023-01-16 21:04:05.531000
stock_market_data/forbes2000/csv/ABTZY.csv   236347  2023-01-16 21:04:05.503000
stock_market_data/forbes2000/csv/ACCYY.csv   336771  2023-01-16 21:04:05.503000
stock_market_data/forbes2000/csv/ACDVF.csv   214509  2023-01-16 21:04:05.516000
stock_market_data/forbes2000/csv/ACFL.csv    508890  2023-01-16 21:04:05.531000
stock_market_data/forbes2000/csv/ACGBY.csv   308686  2023-01-16 21:04:05.537000
stock_market_data/forbes2000/csv/ACGL.csv    740590  2023-01-16 21:04:05.538000
stock_market_data/forbes2000/csv/ACN.csv     573676  2023-01-16 21:04:05.537000
stock_market_data/forbes2000/csv/ACXIF.csv   308324  2023-01-16 21:04:05.565000
stock_market_data/forbes2000/csv/ADDYY.csv   435195  2023-01-16 21:04:05.567000
stock_market_data/forbes2000/csv/ADERY.csv   224647  2023-01-16 21:04:05.543000

In [ ]:
# ============================================================
# CELL 2: Download and unzip the four Kaggle datasets
# ============================================================

# Step 1:
# Define the four dataset slugs we want.
DATASETS = {
    "01_stock_market_data": "paultimothymooney/stock-market-data",
    "02_sp500_financials_news": "sadiqguru/s-and-p-500-stock-data-along-with-financials-and-news",
    "03_sp500_companies_financial_info": "paytonfisher/sp-500-companies-with-financial-information",
    "04_sp500_stocks": "andrewmvd/sp-500-stocks",
}

# Step 2:
# Download each dataset zip and unzip it into its own folder.
for short_name, slug in DATASETS.items():
    out_zip_dir = RAW / short_name
    out_unzip_dir = UNZIPPED / short_name
    out_zip_dir.mkdir(parents=True, exist_ok=True)
    out_unzip_dir.mkdir(parents=True, exist_ok=True)

    print(f"\nDownloading: {slug}")
    !kaggle datasets download -d {slug} -p {str(out_zip_dir)} --unzip

    # Note:
    # We are using --unzip directly, so the files should already be extracted
    # into out_zip_dir. To keep paths simple, we will treat RAW/<dataset> as the
    # extracted folder for inventory + cleaning.
print("\nAll four datasets downloaded.")

Downloading: paultimothymooney/stock-market-data
Dataset URL: https://www.kaggle.com/datasets/paultimothymooney/stock-market-data
License(s): other
Downloading stock-market-data.zip to /content/batch3_kaggle/raw/01_stock_market_data
100% 1.03G/1.03G [00:13<00:00, 80.6MB/s]


Downloading: sadiqguru/s-and-p-500-stock-data-along-with-financials-and-news
Dataset URL: https://www.kaggle.com/datasets/sadiqguru/s-and-p-500-stock-data-along-with-financials-and-news
License(s): MIT
Downloading s-and-p-500-stock-data-along-with-financials-and-news.zip to /content/batch3_kaggle/raw/02_sp500_financials_news
100% 76.4M/76.4M [00:00<00:00, 112MB/s]


Downloading: paytonfisher/sp-500-companies-with-financial-information
Dataset URL: https://www.kaggle.com/datasets/paytonfisher/sp-500-companies-with-financial-information
License(s): ODC Public Domain Dedication and Licence (PDDL)
Downloading sp-500-companies-with-financial-information.zip to /content/batch3_kaggle/raw/03_sp500_companies_financial_info
100% 29.5k/29.5k [00:00<00:00, 29.8MB/s]


Downloading: andrewmvd/sp-500-stocks
Dataset URL: https://www.kaggle.com/datasets/andrewmvd/sp-500-stocks
License(s): CC0-1.0
Downloading sp-500-stocks.zip to /content/batch3_kaggle/raw/04_sp500_stocks
100% 18.7M/18.7M [00:00<00:00, 71.7MB/s]


All four datasets downloaded.

In [ ]:
# ============================================================
# CELL 3: Inventory the files so you can see what exists
# ============================================================

# Step 1:
# Walk through each dataset folder and record file names + sizes.
import os
import pandas as pd

def inventory(root_dir):
    rows = []
    for dirpath, _, filenames in os.walk(root_dir):
        for fname in filenames:
            full_path = os.path.join(dirpath, fname)
            rows.append({
                "relative_path": os.path.relpath(full_path, root_dir),
                "size_mb": round(os.path.getsize(full_path) / (1024 * 1024), 2),
            })
    df = pd.DataFrame(rows)
    if len(df) == 0:
        return df
    return df.sort_values(["relative_path"]).reset_index(drop=True)

inventories = {}

for short_name in DATASETS:
    folder = RAW / short_name
    inv = inventory(folder)
    inventories[short_name] = inv

    print("\n" + "=" * 80)
    print(short_name)
    print("=" * 80)
    display(inv)

    # Save the inventory CSV into the ready folder too.
    out_dir = READY / short_name
    out_dir.mkdir(parents=True, exist_ok=True)
    inv.to_csv(out_dir / f"{short_name}_inventory.csv", index=False)

================================================================================
01_stock_market_data
================================================================================

                                   relative_path  size_mb
0         stock_market_data/forbes2000/csv/A.csv     0.61
1     stock_market_data/forbes2000/csv/AAALY.csv     0.25
2     stock_market_data/forbes2000/csv/AACAY.csv     0.30
3       stock_market_data/forbes2000/csv/AAL.csv     0.44
4       stock_market_data/forbes2000/csv/AAP.csv     0.54
...                                          ...      ...
9205       stock_market_data/sp500/json/XYL.json     0.88
9206       stock_market_data/sp500/json/YUM.json     2.01
9207       stock_market_data/sp500/json/ZBH.json     1.70
9208      stock_market_data/sp500/json/ZION.json     3.15
9209       stock_market_data/sp500/json/ZTS.json     0.78

[9210 rows x 2 columns]

================================================================================
02_sp500_financials_news
================================================================================

                     relative_path  size_mb
0              01_company_info.csv     1.15
1    02_company_news_sentiment.csv    10.23
2     03_company_balance_sheet.csv     7.62
3        04_company_financials.csv     4.99
4           05_company_filings.csv     4.67
..                             ...      ...
529             price_data/YUM.csv     0.38
530             price_data/ZBH.csv     0.38
531            price_data/ZBRA.csv     0.37
532            price_data/ZION.csv     0.38
533             price_data/ZTS.csv     0.31

[534 rows x 2 columns]

================================================================================
03_sp500_companies_financial_info
================================================================================

    relative_path  size_mb
0  financials.csv     0.09

================================================================================
04_sp500_stocks
================================================================================

         relative_path  size_mb
0  sp500_companies.csv     0.77
1      sp500_index.csv     0.05
2     sp500_stocks.csv    91.85

In [ ]:
# ============================================================
# CELL 4: Decide which CSV files are relevant
# ============================================================

# Step 1:
# This helper finds CSV files recursively.
from pathlib import Path

def find_csvs(root_dir):
    return sorted([str(p) for p in Path(root_dir).rglob("*.csv")])

# Step 2:
# Build a simple default selection rule:
# - Dataset 1: keep only CSV files whose path contains 'sp500'
# - Datasets 2/3/4: keep all CSV files
#
# This keeps the notebook simple and aligned with your current goal.
selected_files = {}

for short_name in DATASETS:
    csvs = find_csvs(RAW / short_name)

    if short_name == "01_stock_market_data":
        selected = [p for p in csvs if "sp500" in p.lower()]
    else:
        selected = csvs

    selected_files[short_name] = selected

# Step 3:
# Print the selected files so you can quickly sanity-check them.
for short_name, files_list in selected_files.items():
    print("\n" + "-" * 80)
    print(f"Selected CSV files for {short_name}:")
    print("-" * 80)
    for p in files_list:
        print(p)

# Optional manual override:
# If you want, you can replace any selected_files[...] list manually after this cell runs.
# Example:
# selected_files["02_sp500_financials_news"] = [
#     "/content/batch3_kaggle/raw/02_sp500_financials_news/company_news_sentiment.csv"
# ]

--------------------------------------------------------------------------------
Selected CSV files for 01_stock_market_data:
--------------------------------------------------------------------------------
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/A.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AAL.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AAP.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AAPL.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ABBV.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ABC.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ABMD.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ABT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ACN.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ADI.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ADM.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ADP.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ADSK.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AEE.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AEP.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AIZ.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AJG.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AKAM.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ALB.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ALGN.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ALK.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ALLE.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ALTR.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AMAT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AMD.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AME.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AMGN.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AMP.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AMT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AMZN.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ANET.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AON.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AOS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/APA.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/APD.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/APH.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ARE.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ATVI.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AVB.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AVY.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AWK.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AXP.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AZO.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BA.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BAC.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BAX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BBY.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BDX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BEN.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BF-A.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BHI.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BIIB.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BIO.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BK.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BLK.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BMRA.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BMY.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BR.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BRK-A.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BSHI.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BSX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BWA.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BXP.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/C.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CAG.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CAH.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CAT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CB.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CCI.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CDE.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CDNS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CF.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CFG.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CHD.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CHRW.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CHTR.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CINF.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CL.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CLX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CME.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CMG.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CMI.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CNC.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CNP.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CNWT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/COO.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/COP.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/COST.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/COTY.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/COWN.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CPB.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CPICQ.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CPRT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CRM.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CSCO.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CTAS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CTQ.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CTSH.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CUK.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/D.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DAL.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DE.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DFS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DG.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DGX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DHI.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DIS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DLTR.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DOV.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DPZ.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DRE.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DRI.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DTE.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DVA.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DXCM.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EA.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EBAY.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ECL.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ED.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EFX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EIX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EL.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EMN.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EMR.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ENS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EOG.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EQIX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EQR.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ES.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ESS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EW.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EXR.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/F.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FANG.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FAST.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FBHS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FCX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FDX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FE.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FFIV.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FIS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FISV.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FITB.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FLS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FLT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FMBM.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FMC.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FN.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FPLPF.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FRC.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FRMC.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FRT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FTI.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GD.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GE.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GGG.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GILD.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GIS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GM.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GOOG.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GPC.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GPN.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GRMN.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GS-PJ.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GWW.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HAL.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HAS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HBAN.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HBI.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HCA.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HD.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HES.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HII.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HLT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HOLX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HON.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HPE.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HPQ.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HRB.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HRL.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HSIC.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HST.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HSY.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HTLF.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HUM.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IBM.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ICE.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IDXX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IEX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IFF.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ILMN.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/INTH.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/INTU.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IP.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IPGP.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IR.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IRM.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ISRG.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ITW.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IVZ.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/JBHT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/JCI.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/JKHY.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/JNJ.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/JNPR.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/JPM.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/K.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KACPF.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KEY.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KEYS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KGNR.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KHC.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KIM.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KMB.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KMX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KO.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KR.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KSS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LBTYA.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LDOS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LEG.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LH.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LKQ.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LMT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LNC.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LNT.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LOW.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LRCX.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LUV.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LVS.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LYB.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LYV.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MAA.csv
/content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MAR.csv

In [ ]:
# ============================================================
# CELL 5: Simple cleaning helpers
# ============================================================

# This cell mirrors the spirit of your larger notebook:
# read data -> clean it -> write cleaned outputs.
#
# We are intentionally skipping the parquet step here because your
# immediate goal is Batch 3 upload, not a giant warehouse rewrite.

import re
import numpy as np

def snake_case(name):
    # Convert column names to lowercase snake_case.
    name = str(name).strip()
    name = re.sub(r"[^A-Za-z0-9]+", "_", name)
    name = re.sub(r"_+", "_", name)
    return name.strip("_").lower()

def normalize_ticker(x):
    # Standardize ticker-like values:
    # - uppercase
    # - strip spaces
    # - unify some punctuation
    if pd.isna(x):
        return x
    x = str(x).strip().upper()
    x = x.replace(".", "-").replace("/", "-").replace(" ", "")
    return x

def maybe_parse_dates(df):
    # Parse columns that look date-like.
    for col in df.columns:
        if any(key in col for key in ["date", "published", "time", "timestamp"]):
            try:
                df[col] = pd.to_datetime(df[col], errors="coerce")
            except Exception:
                pass
    return df

def normalize_strings(df):
    # Strip whitespace from object columns.
    for col in df.columns:
        if df[col].dtype == "object":
            df[col] = df[col].astype(str).str.strip()
            df.loc[df[col].isin(["nan", "None", "NaT"]), col] = np.nan
    return df

def normalize_ticker_columns(df):
    # Normalize likely ticker/symbol columns.
    ticker_like = [c for c in df.columns if c in {"ticker", "symbol", "ticker_in_source"} or "ticker" in c or "symbol" in c]
    for col in ticker_like:
        df[col] = df[col].apply(normalize_ticker)
    return df

def clean_price_like(df):
    # Apply the notebook-style price cleaning:
    # - drop rows missing core fields if present
    # - remove negative numeric values from price/volume fields
    # - sort by ticker/date if present
    essential_candidates = [c for c in ["date", "trading_date", "close", "volume"] if c in df.columns]
    if essential_candidates:
        df = df.dropna(subset=essential_candidates)

    numeric_cols = [c for c in ["open", "high", "low", "close", "adj_close", "adjusted_close", "volume"] if c in df.columns]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")
        df = df[df[col].isna() | (df[col] >= 0)]

    sort_cols = [c for c in ["ticker", "symbol", "date", "trading_date"] if c in df.columns]
    if sort_cols:
        df = df.sort_values(sort_cols)

    return df

def clean_company_like(df):
    # Deduplicate likely company reference rows.
    preferred_keys = []
    for key_set in [["ticker"], ["symbol"], ["ticker", "company_name"], ["symbol", "company_name"]]:
        if all(k in df.columns for k in key_set):
            preferred_keys = key_set
            break
    if preferred_keys:
        df = df.drop_duplicates(subset=preferred_keys)
    else:
        df = df.drop_duplicates()
    return df

def clean_news_like(df):
    # Basic news cleaning:
    # - sort by published time if present
    # - dedupe by url if present, otherwise by title+published_at if possible
    sort_cols = [c for c in ["published_at", "date", "published_date"] if c in df.columns]
    if sort_cols:
        df = df.sort_values(sort_cols)

    if "url" in df.columns:
        df = df.drop_duplicates(subset=["url"])
    elif all(c in df.columns for c in ["title", "published_at"]):
        df = df.drop_duplicates(subset=["title", "published_at"])
    else:
        df = df.drop_duplicates()

    return df

def classify_table(df):
    cols = set(df.columns)
    if {"open", "high", "low", "close"} & cols:
        return "price"
    if {"title", "url", "published_at"} & cols:
        return "news"
    if {"sector", "industry", "company_name", "ticker", "symbol"} & cols:
        return "company"
    return "generic"

def basic_clean(df):
    # 1) normalize column names
    df.columns = [snake_case(c) for c in df.columns]

    # 2) trim strings
    df = normalize_strings(df)

    # 3) parse date-like columns
    df = maybe_parse_dates(df)

    # 4) normalize ticker-like columns
    df = normalize_ticker_columns(df)

    # 5) remove exact duplicates first
    df = df.drop_duplicates()

    # 6) apply table-specific cleaning
    table_type = classify_table(df)
    if table_type == "price":
        df = clean_price_like(df)
    elif table_type == "company":
        df = clean_company_like(df)
    elif table_type == "news":
        df = clean_news_like(df)
    else:
        df = df.drop_duplicates()

    return df, table_type

In [ ]:
# ============================================================
# CELL 6: Clean the selected files and export Batch 3-ready outputs
# ============================================================

# Output strategy:
# For every selected CSV file, create:
# - a cleaned SAMPLE file (first 300 rows) for easy upload
# - a cleaned FULL file if it is small enough
# - cleaned CHUNKS if the full file is too large
# - a small metadata row in a per-dataset cleaning log

MAX_FULL_MB = 45
SAMPLE_ROWS = 300
CHUNK_ROWS = 150000

def file_size_mb(path):
    return os.path.getsize(path) / (1024 * 1024)

def save_chunked_csv(df, base_path, rows_per_chunk=150000):
    for i in range(0, len(df), rows_per_chunk):
        chunk = df.iloc[i:i + rows_per_chunk]
        chunk_path = f"{base_path}_part{i // rows_per_chunk + 1:02d}.csv"
        chunk.to_csv(chunk_path, index=False)

for short_name, files_list in selected_files.items():
    out_dir = READY / short_name
    out_dir.mkdir(parents=True, exist_ok=True)

    log_rows = []

    for file_path in files_list:
        try:
            src = Path(file_path)
            print(f"\nProcessing: {src}")

            # Step 1: read CSV
            df = pd.read_csv(src)

            # Step 2: clean it
            cleaned, table_type = basic_clean(df)

            # Step 3: build output names
            stem = snake_case(src.stem)
            sample_path = out_dir / f"{stem}__sample.csv"
            full_path = out_dir / f"{stem}__cleaned.csv"

            # Step 4: always save a sample
            cleaned.head(SAMPLE_ROWS).to_csv(sample_path, index=False)

            # Step 5: save full cleaned file if small enough; otherwise chunk it
            temp_full = out_dir / f"{stem}__temp_full.csv"
            cleaned.to_csv(temp_full, index=False)
            full_size = file_size_mb(temp_full)

            if full_size <= MAX_FULL_MB:
                temp_full.rename(full_path)
                saved_mode = "full"
            else:
                temp_full.unlink(missing_ok=True)
                save_chunked_csv(cleaned, str(out_dir / f"{stem}__chunk"), rows_per_chunk=CHUNK_ROWS)
                saved_mode = "chunked"

            log_rows.append({
                "source_file": str(src),
                "table_type_guess": table_type,
                "raw_rows": len(df),
                "cleaned_rows": len(cleaned),
                "sample_file": sample_path.name,
                "saved_mode": saved_mode,
            })

        except Exception as e:
            log_rows.append({
                "source_file": str(file_path),
                "table_type_guess": "ERROR",
                "raw_rows": None,
                "cleaned_rows": None,
                "sample_file": None,
                "saved_mode": f"error: {e}",
            })
            print(f"Error processing {file_path}: {e}")

    # Save per-dataset cleaning log
    pd.DataFrame(log_rows).to_csv(out_dir / f"{short_name}_cleaning_log.csv", index=False)

print("\nBatch 3-ready files created.")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/A.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AAL.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AAP.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AAPL.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ABBV.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ABC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ABMD.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ABT.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ACN.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ADI.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ADM.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ADP.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ADSK.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AEE.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AEP.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AIZ.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AJG.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AKAM.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ALB.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ALGN.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ALK.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ALLE.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ALTR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AMAT.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AMD.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AME.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AMGN.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AMP.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AMT.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AMZN.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ANET.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AON.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AOS.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/APA.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/APD.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/APH.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ARE.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ATVI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AVB.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AVY.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AWK.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AXP.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/AZO.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BA.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BAC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BAX.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BBY.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BDX.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BEN.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BF-A.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BHI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BIIB.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BIO.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BK.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BLK.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BMRA.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BMY.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BRK-A.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BSHI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BSX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BWA.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/BXP.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/C.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CAG.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CAH.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CAT.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CB.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CCI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CDE.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CDNS.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CF.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CFG.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CHD.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CHRW.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CHTR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CINF.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CL.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CLX.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CME.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CMG.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CMI.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CNC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CNP.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CNWT.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/COO.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/COP.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/COST.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/COTY.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/COWN.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CPB.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CPICQ.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CPRT.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CRM.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CSCO.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CTAS.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CTQ.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CTSH.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/CUK.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/D.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DAL.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DE.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DFS.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DG.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DGX.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DHI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DIS.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DLTR.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DOV.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DPZ.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DRE.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DRI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DTE.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DVA.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/DXCM.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EA.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EBAY.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ECL.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ED.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EFX.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EIX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EL.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EMN.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EMR.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ENS.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EOG.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EQIX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EQR.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ES.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ESS.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EW.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/EXR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/F.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FANG.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FAST.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FBHS.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FCX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FDX.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FE.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FFIV.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FIS.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FISV.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FITB.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FLS.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FLT.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FMBM.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FMC.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FN.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FPLPF.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FRC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FRMC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FRT.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/FTI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GD.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GE.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GGG.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GILD.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GIS.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GM.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GOOG.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GPC.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GPN.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GRMN.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GS-PJ.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/GWW.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HAL.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HAS.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HBAN.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HBI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HCA.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HD.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HES.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HII.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HLT.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HOLX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HON.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HPE.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HPQ.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HRB.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HRL.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HSIC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HST.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HSY.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HTLF.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/HUM.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IBM.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ICE.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IDXX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IEX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IFF.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ILMN.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/INTH.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/INTU.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IP.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IPGP.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IR.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IRM.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ISRG.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IT.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ITW.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/IVZ.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/JBHT.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/JCI.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/JKHY.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/JNJ.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/JNPR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/JPM.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/K.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KACPF.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KEY.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KEYS.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KGNR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KHC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KIM.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KMB.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KMX.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KO.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/KSS.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LBTYA.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LDOS.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LEG.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LH.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LKQ.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LMT.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LNC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LNT.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LOW.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LRCX.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LUV.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LVS.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LYB.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/LYV.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MAA.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MAR.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MCD.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MCHP.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MCK.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MCO.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MDLZ.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MDT.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MET.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MGM.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MHK.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MKTX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MLM.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MMC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MMM.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MNST.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MO.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MOS.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MPC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MRCR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MRK.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MRO.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MS-PF.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MSCI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MSFT.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MSI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/MU.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NCLH.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NCTKF.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NDAQ.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NEE.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NEOG.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NFLX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NI.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NLSN.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NMHLY.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NOC.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NOK.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NOV.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NOW.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NOXL.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NRG.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NSC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NTAP.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NTRA.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NTRR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NTRS.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NVR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NVRO.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/NWL.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/O.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ODFL.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/OKE.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/OMC.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ORLY.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/OXY.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PAYX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PCAR.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PEG.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PEP.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PFE.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PG.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PH.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PHM.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PKG.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PKI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PLD.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PM.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PNR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PNW.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PNWRF.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PPG.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PRU.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PSX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PVH.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PWR.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/PXD.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/QRVO.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/RCL.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/RE.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/REG.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/REGN.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/RF.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/RHI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/RIBT.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/RJF.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/RL.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/RLI.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/RMD.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ROK.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ROL.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ROP.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ROST.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/RSG.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/RSNHF.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/RXMD.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SBUX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SCHW.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SEE.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SEGXF.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SHW.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SIVB.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SLB.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SLG.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SNPS.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SO.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SONC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SPG.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SRE.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SRG.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/STT.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/STX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/STZ-B.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SWK.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SWKS.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SYF.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/SYK.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/T.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TAP.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TCYSF.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TEL.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TIME.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TJX.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TMO.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TMUS.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TRAUF.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TROW.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TRV.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TSCO.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TSN.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TTWO.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TW.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TWTR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TXN.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TXT.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/TYL.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/UA.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/UAL.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/UDR.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/UEEC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/UHS.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ULTA.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/UNM.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/UNP.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/UPS.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/URI.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/USB.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/V.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/VFC.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/VMC.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/VRSK.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/VRSN.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/VTR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/VZ.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WAT.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WBA.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WDC.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WEC.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WHR.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WM.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WMB.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WRB.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WRK.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WSPOF.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WST.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WU.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WY.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/WYNN.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/XEL.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/XLEFF.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/XOM.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/XYL.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/YUM.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ZBH.csv

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ZION.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")
/tmp/ipykernel_779/999185835.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/01_stock_market_data/stock_market_data/sp500/csv/ZTS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/01_company_info.csv

/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/02_company_news_sentiment.csv

/tmp/ipykernel_779/999185835.py:37: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors="coerce")

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/03_company_balance_sheet.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/04_company_financials.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/05_company_filings.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/06_company_officers.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/A.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AAL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AAP.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AAPL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ABBV.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ABNB.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ABT.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ACGL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ACN.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ADBE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ADI.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ADM.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ADP.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ADSK.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AEE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AEP.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AES.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AFL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AIG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AIV.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AIZ.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AJG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AKAM.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ALB.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ALGN.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ALK.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ALL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ALLE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AMAT.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AMCR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AMD.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AME.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AMGN.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AMP.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AMT.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AMTM.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AMZN.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ANET.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AON.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AOS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/APA.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/APD.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/APH.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/APTV.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ARE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ATO.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AVB.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AVGO.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AVY.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AWK.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AXON.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AXP.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/AZO.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BA.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BAC.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BALL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BAX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BBY.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BDX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BEN.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BIIB.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BIO.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BK.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BKNG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BKR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BLDR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BLK.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BMY.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BRO.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BSX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BWA.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/BXP.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/C.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CAG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CAH.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CARR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CAT.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CB.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CBOE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CBRE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CCI.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CCL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CDNS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CDW.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CEG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CF.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CFG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CHD.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CHRW.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CHTR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CI.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CINF.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CLSK.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CLX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CMA.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CMCSA.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CME.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CMG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CMI.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CMS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CNC.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CNP.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/COF.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/COO.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/COP.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/COR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/COST.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/COTY.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CPAY.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CPB.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CPRT.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CPT.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CRL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CRM.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CRWD.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CSCO.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CSGP.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CSX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CTAS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CTRA.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CTSH.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CTVA.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CVS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CVX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/CZR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/D.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DAL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DAY.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DD.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DECK.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DELL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DGX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DHI.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DHR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DIS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DLR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DLTR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DOC.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DOV.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DOW.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DPZ.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DRI.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DTE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DUK.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DVA.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DVN.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DXC.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/DXCM.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EA.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EBAY.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ECL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ED.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EFX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EIX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ELV.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EMN.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EMR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ENPH.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EOG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EPAM.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EQIX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EQR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EQT.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ERIE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ES.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ESS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ETN.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/ETR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EVRG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EW.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EXC.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EXPD.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EXPE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/EXR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/F.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FANG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FAST.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FB.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FCX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FDS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FDX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FFIV.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FICO.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FIS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FISV.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FITB.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FLS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FMC.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FOX.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FOXA.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FRT.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FSLR.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FTI.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FTNT.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/FTV.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GD.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GDDY.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GE.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GEHC.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GEN.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GEV.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GILD.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GIS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GLW.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GM.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GNRC.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GOOG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GOOGL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GPC.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GPN.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GRMN.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/GWW.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/HAL.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/HAS.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/HBAN.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/HCA.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/HD.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/HIG.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/HII.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/HLT.csv

Processing: /content/batch3_kaggle/raw/02_sp500_financials_news/price_data/HOLX.csv


/tmp/ipykernel_779/999185835.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors="coerce")

Batch 3-ready files created.

In [ ]:
# ============================================================
# CELL 7: Zip each dataset folder and a master folder, then download
# ============================================================

import shutil
from google.colab import files

# Step 1:
# Create one zip per dataset folder.
dataset_zip_paths = []

for short_name in DATASETS:
    folder_to_zip = READY / short_name
    zip_base = ZIPS / short_name
    zip_path = shutil.make_archive(str(zip_base), "zip", root_dir=str(folder_to_zip))
    dataset_zip_paths.append(zip_path)
    print("Created:", zip_path)

# Step 2:
# Create one master zip containing all Batch 3-ready outputs.
master_zip = shutil.make_archive(str(ZIPS / "batch3_ready_all"), "zip", root_dir=str(READY))
print("Created master zip:", master_zip)

# Step 3:
# Download strategy:
# - Start by downloading the individual dataset zips.
# - If the master zip is manageable, download that too.
#
# Uncomment whichever downloads you want.

# for zp in dataset_zip_paths:
#     files.download(zp)

# files.download(master_zip)

print("\nDone. You can now download the zip(s) from the file browser or uncomment files.download(...).")

Created: /content/batch3_kaggle/zips/01_stock_market_data.zip
Created: /content/batch3_kaggle/zips/02_sp500_financials_news.zip
Created: /content/batch3_kaggle/zips/03_sp500_companies_financial_info.zip
Created: /content/batch3_kaggle/zips/04_sp500_stocks.zip
Created master zip: /content/batch3_kaggle/zips/batch3_ready_all.zip

Done. You can now download the zip(s) from the file browser or uncomment files.download(...).

In [ ]:
# ============================================================
# CELL: Combine all cleaned stock_market_data files into one CSV
# ============================================================

# Goal:
# Take all per-ticker cleaned CSV files from Dataset 1
# and combine them into one staging CSV that is easier
# to load into PostgreSQL later.
#
# This is recommended as a SOURCE-SPECIFIC staging file.
# It is NOT meant to replace your final normalized price_daily table.

from pathlib import Path
import pandas as pd

# Step 1:
# Point to the folder that contains the cleaned Dataset 1 files.
SRC_DIR = Path("/content/batch3_kaggle/batch3_ready/01_stock_market_data")

# Step 2:
# Choose an output file name for the combined staging CSV.
OUT_FILE = SRC_DIR / "stock_market_data_sp500_combined.csv"

# Step 3:
# Find all cleaned per-ticker CSV files.
# We only want files ending in "__cleaned.csv".
cleaned_files = sorted(SRC_DIR.glob("*__cleaned.csv"))

print(f"Found {len(cleaned_files)} cleaned files.")

frames = []

# Step 4:
# Read each file, infer ticker from the file name,
# standardize column names a bit, and append it to a list.
for fp in cleaned_files:
    df = pd.read_csv(fp)

    # Infer ticker from file name:
    # e.g. "aapl__cleaned.csv" -> "AAPL"
    ticker = fp.stem.replace("__cleaned", "").upper()

    # Add ticker + source columns so the combined file
    # still keeps useful provenance.
    df["ticker"] = ticker
    df["source_name"] = "stock_market_data_sp500"
    df["source_file"] = fp.name

    # Rename columns to match your target schema more closely.
    if "date" in df.columns:
        df = df.rename(columns={"date": "trading_date"})
    if "adjusted_close" in df.columns and "adj_close" not in df.columns:
        df = df.rename(columns={"adjusted_close": "adj_close"})

    # Reorder columns so the output is cleaner.
    preferred_order = [
        "ticker",
        "trading_date",
        "open",
        "high",
        "low",
        "close",
        "adj_close",
        "volume",
        "source_name",
        "source_file",
    ]

    ordered_cols = [c for c in preferred_order if c in df.columns]
    extra_cols = [c for c in df.columns if c not in ordered_cols]
    df = df[ordered_cols + extra_cols]

    frames.append(df)

# Step 5:
# Combine all per-ticker DataFrames into one big DataFrame.
combined = pd.concat(frames, ignore_index=True)

# Step 6:
# Final cleanup for the combined staging file.
if "trading_date" in combined.columns:
    combined["trading_date"] = pd.to_datetime(
        combined["trading_date"], errors="coerce"
    )

# Drop rows missing the fields you definitely need.
required_cols = [c for c in ["ticker", "trading_date", "close"] if c in combined.columns]
if required_cols:
    combined = combined.dropna(subset=required_cols)

# Optional de-dup:
# Since each file is one ticker, this mainly protects against
# accidental duplicate rows after concatenation.
dedupe_cols = [c for c in [
    "ticker", "trading_date", "open", "high", "low", "close", "adj_close", "volume"
] if c in combined.columns]

if dedupe_cols:
    combined = combined.drop_duplicates(subset=dedupe_cols)

# Sort for sanity.
sort_cols = [c for c in ["ticker", "trading_date"] if c in combined.columns]
if sort_cols:
    combined = combined.sort_values(sort_cols)

# Step 7:
# Save the combined CSV.
combined.to_csv(OUT_FILE, index=False)

print(f"Combined file saved to: {OUT_FILE}")
print(f"Final shape: {combined.shape}")
display(combined.head())

Found 409 cleaned files.
Combined file saved to: /content/batch3_kaggle/batch3_ready/01_stock_market_data/stock_market_data_sp500_combined.csv
Final shape: (2515911, 10)

,ticker,trading_date,open,high,low,close,adj_close,volume,source_name,source_file
0,A,1999-11-18,32.546494,35.765381,28.612303,31.473534,26.929760,62546380.0,stock_market_data_sp500,a__cleaned.csv
1,A,1999-11-19,30.713518,30.758226,28.478184,28.880545,24.711119,15234146.0,stock_market_data_sp500,a__cleaned.csv
2,A,1999-11-22,29.551144,31.473534,28.657009,31.473534,26.929760,6577870.0,stock_market_data_sp500,a__cleaned.csv
3,A,1999-11-23,30.400572,31.205294,28.612303,28.612303,24.481602,5975611.0,stock_market_data_sp500,a__cleaned.csv
4,A,1999-11-24,28.701717,29.998213,28.612303,29.372318,25.131901,4843231.0,stock_market_data_sp500,a__cleaned.csv

In [ ]:
# ============================================================
# COLAB CELL: Build a load-ready Dataset 1 CSV with only 2016+ rows
# ============================================================

import pandas as pd
from pathlib import Path
import os

# Step 1:
# Point to the combined Dataset 1 CSV you already made earlier.
SRC = Path("/content/batch3_kaggle/batch3_ready/01_stock_market_data/stock_market_data_sp500_combined.csv")

# Step 2:
# Choose the output path for the smaller, database-load-ready file.
OUT = SRC.with_name("d1_prices_load_2016plus.csv")

# Step 3:
# Define the cutoff date and chunk size.
# We use chunking so Colab does not have to hold the whole file in memory.
CUTOFF = pd.Timestamp("2016-01-01")
CHUNK_SIZE = 200_000

# Step 4:
# Read only the header first so we can detect column names safely.
header = pd.read_csv(SRC, nrows=0)

# Step 5:
# Figure out what the date column is called.
# Your combined file should already have trading_date, but this makes the cell robust.
date_col = "trading_date" if "trading_date" in header.columns else "date"

# Step 6:
# Figure out what the ticker column is called.
ticker_col = "ticker" if "ticker" in header.columns else "symbol"

# Step 7:
# Decide which columns we actually want in the DB load file.
# This matches the PostgreSQL staging table stg_d1_prices_raw.
keep_cols = [
    c for c in [
        ticker_col,
        date_col,
        "open",
        "high",
        "low",
        "close",
        "adj_close",
        "volume",
        "source_name",
        "source_file",
    ]
    if c in header.columns
]

print("Using date column :", date_col)
print("Using ticker column:", ticker_col)
print("Keeping columns    :", keep_cols)

# Step 8:
# Initialize counters and trackers for QA.
rows_in = 0
rows_out = 0
first_write = True
unique_tickers = set()
min_kept = None
max_kept = None

# Step 9:
# Process the file in chunks.
for chunk in pd.read_csv(SRC, chunksize=CHUNK_SIZE, low_memory=False):
    rows_in += len(chunk)

    # Parse the date column safely.
    chunk[date_col] = pd.to_datetime(chunk[date_col], errors="coerce")

    # Keep only 2016-01-01 and later.
    chunk = chunk[chunk[date_col] >= CUTOFF].copy()

    # Rename columns to the exact names the staging table expects.
    if ticker_col != "ticker":
        chunk = chunk.rename(columns={ticker_col: "ticker"})
    if date_col != "trading_date":
        chunk = chunk.rename(columns={date_col: "trading_date"})

    # Keep only the expected load columns, in the expected order.
    final_cols = [
        c for c in [
            "ticker",
            "trading_date",
            "open",
            "high",
            "low",
            "close",
            "adj_close",
            "volume",
            "source_name",
            "source_file",
        ]
        if c in chunk.columns
    ]
    chunk = chunk[final_cols]

    # Track some quick QA stats.
    if not chunk.empty:
        rows_out += len(chunk)
        if "ticker" in chunk.columns:
            unique_tickers.update(
                chunk["ticker"].dropna().astype(str).str.upper().tolist()
            )

        chunk_min = chunk["trading_date"].min()
        chunk_max = chunk["trading_date"].max()

        if min_kept is None or chunk_min < min_kept:
            min_kept = chunk_min
        if max_kept is None or chunk_max > max_kept:
            max_kept = chunk_max

        # Write the filtered chunk to disk.
        chunk.to_csv(
            OUT,
            mode="w" if first_write else "a",
            header=first_write,
            index=False
        )
        first_write = False

# Step 10:
# Print the summary so you can sanity-check the result.
print("\nDone.")
print(f"Rows before filter : {rows_in:,}")
print(f"Rows after filter  : {rows_out:,}")
print(f"Rows removed       : {rows_in - rows_out:,}")
print(f"Unique tickers kept: {len(unique_tickers):,}")
print(f"Date range kept    : {min_kept} to {max_kept}")
print(f"Output file        : {OUT}")
print(f"Output file size   : {os.path.getsize(OUT) / (1024 * 1024):.2f} MB")

# Step 11:
# Optional: preview the first few rows of the filtered file.
preview = pd.read_csv(OUT, nrows=5)
display(preview)

Using date column : trading_date
Using ticker column: ticker
Keeping columns    : ['ticker', 'trading_date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'source_name', 'source_file']

Done.
Rows before filter : 2,515,911
Rows after filter  : 547,498
Rows removed       : 1,968,413
Unique tickers kept: 409
Date range kept    : 2016-01-02 00:00:00 to 2022-12-12 00:00:00
Output file        : /content/batch3_kaggle/batch3_ready/01_stock_market_data/d1_prices_load_2016plus.csv
Output file size   : 80.26 MB

,ticker,trading_date,open,high,low,close,adj_close,volume,source_name,source_file
0,A,2016-01-04,41.060001,41.189999,40.340000,40.689999,38.468792,3287300.0,stock_market_data_sp500,a__cleaned.csv
1,A,2016-01-05,40.730000,40.950001,40.340000,40.549999,38.336441,2587200.0,stock_market_data_sp500,a__cleaned.csv
2,A,2016-01-06,40.240002,40.990002,40.049999,40.730000,38.506611,2103600.0,stock_market_data_sp500,a__cleaned.csv
3,A,2016-01-07,40.139999,40.150002,38.810001,39.000000,36.871059,3504300.0,stock_market_data_sp500,a__cleaned.csv
4,A,2016-01-08,39.220001,39.709999,38.470001,38.590000,36.483444,3736700.0,stock_market_data_sp500,a__cleaned.csv

## What you should for Batch 3

From the `batch3_ready` outputs, send in this order:

### Batch 3A
- each `*_inventory.csv`
- each `*_cleaning_log.csv`
- the `__sample.csv` files

### Batch 3B
- the smaller `__cleaned.csv` files

### Batch 3C
- any `__chunk_partXX.csv` files for the large tables

This keeps the intake clean and makes entity-resolution review much easier.